version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .data/mongo:/data/db
  
  app1:
    container_name: app1
    build: 
      context: ./app1/
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./app1:/app
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://mongo:27017/app1
    depends_on:
      - mongo
      - kafka
  
  app2:
    container_name: app2
    build: 
      context: ./app2/
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    volumes:
      - ./app2:/app
    environment:
      - PORT=4001
      - MONGO_URL=mongodb://mongo:27017/app2
    depends_on:
      - mongo
      - kafka

