version: '3'

services:
  app1:
    container_name: app1
    build: 
      context: ./app1/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./app1:/app
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://mongo:27017/app1
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-network
    
  app2:
    container_name: app2
    build: 
      context: ./app2/
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./app2:/app
    environment:
      - PORT=4001
      - MONGO_URL=mongodb://mongo:27017/app2
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-network

networks:
  kafka-network:
    external:
      name: kafka-app_kafka-network