version: '3'
services:
  app:
    build:
      context: ./app3/
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-network

networks:
  kafka-network:
    external:
      name: kafka-app_kafka-network
